version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./api/:/var/www/html/
    links:
      - mysql 
    container_name: php
    restart: always
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./api/:/var/www/html/
    container_name: apache
  mysql:
    image: mariadb:${MYSQL_VERSION:-latest}
    volumes:
      - ./dump/fantamanajer.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: fantamanajer
      MYSQL_USER: fantamanajerUser
      MYSQL_PASSWORD: banana
    ports:
      - "3307:3306"
    container_name: mysql
  
networks:
  frontend:
  backend:
